---
# Credentials for CVP and EOS Switches
ansible_user: arista
ansible_password: "{{ lookup('env', 'LABPASSPHRASE') }}"
ansible_network_os: arista.eos.eos
# Configure privilege escalation
ansible_become: true
ansible_become_method: enable
# HTTPAPI configuration
ansible_connection: httpapi
ansible_httpapi_port: 443
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_python_interpreter: $(which python3)
avd_data_validation_mode: error

# arista.avd.cv_deploy role parameters
cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc0NTk4NTk2MjA0NjMzNzg2NjgsImRzbiI6IkhhcnJ5IiwiZHN0IjoiYWNjb3VudCIsImV4cCI6MjAxMTY1ODk2OCwiaWF0IjoxNzU4MTYxMzc0LCJvZ2kiOjMsIm9nbiI6IkRlZmF1bHQiLCJzaWQiOiJhYzkwMmJlOTI1YWQ4OGU2YmM4NzcyZWY0ZTE1MGQ4ODJiNzM2ZDRiNzc1MmMxYThlYmIyODE5YWZjNTdhOGEyLXNNZG5PcWZ1OFk1Nkh3cHZlOFZDNWw5VGdicjJZblo3Sm9ick8wbmoifQ.RCIlWi1o-_TvM0jsuiriMM5fLYfYbQEQLAmcVUkAXgd_SEHXa7UQUqxhrSyfE5LwH0hp8MOUT92_0xoU8qtR_-9rSkrtBZTB4Z_ZTIdwNOChkiFwIEu0bYFAnu10QpAmQmGSlS70fVPu4Yg7iKbHk6h63i0xHlOWxmDSaH4OMFJfHS9QeacEm5_vEyGHElSXBxLsX7t7s4JNWzNnejx1ScoGab3AMLQfsSk38VHqWq1_vFj9nV9x9ZOHRnpoiYSL3pzVmYbwmVu1Lb0LPZgzNiQNe8LYbBwLbFAv_TTY9NFOA0FFfO7Hiv0Py_LwMh9kwrW4e5-jwcpQ94ULD6N3FJaDH1-wdRGxJ0cBIALZkZ4GIokcVrt0iwhdZ5BOUDMH3jDJaha1QhHiJuLM6pfshc2YyBF6eoQ0I4fjxergno5WoexByI6PIauN25SjcfyqUFu50EilJEuAHQgvONuvYCp1ZDl6xOxRSVhanIXUWnhCyhJgXYTpgcg7jOo2Q6sbXUr3aUlpOX3ukMUc6ybffzq2tUOM92LXIkYM_0MC9n9NyGo90S4QAmWHr6uvct5HyUHXMxM5ghjdxhcZr0sCu_cF1sG-8opu0kgWmd_pUcIa6XSZdPw2zw-TFbZ8SaYZxgC9JQW8ELBLeajxs3Fzrg-6uc_RDhLwUBD61lmRP1s
cv_server: cvp
cv_verify_certs: false

# Local Users
local_users:
  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: "{{ ansible_password | password_hash('sha512', salt='arista', rounds=5000) }}"
    ssh_key: "{{ lookup('ansible.builtin.file', '~/.ssh/id_rsa.pub') }}"

# AAA
aaa_authorization:
  exec:
    default: local

# OOB Management network default gateway.
mgmt_gateway: 192.168.0.1
mgmt_interface_vrf: default

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp:
  servers:
    - name: 192.168.0.1
      iburst: true
      local_interface: Management0

# Domain/DNS
dns_domain: atd.lab

# TerminAttr
daemon_terminattr:
  # Address of the gRPC server on CloudVision
  # TCP 9910 is used on on-prem
  # TCP 443 is used on CV as a Service
  cvaddrs: # For single cluster
    - 192.168.0.5:9910
  # Authentication scheme used to connect to CloudVision
  cvauth:
    method: token
    token_file: "/tmp/token"
  # Exclude paths from Sysdb on the ingest side
  ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent
  # Exclude paths from the shared memory table
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata

# Point to Point Links MTU Override for Lab
p2p_uplinks_mtu: 1500

# CVP node variables
cv_collection: v3
execute_tasks: true
